import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import HomePage from "../components/main/HomePage";
import Logos_first_row from "./clients/logos_first_row"
import Map from '../components/main/Map';
import Main_services from '../components/main/Main_services';
import LetsWorkTogether from '../components/main/LetsWorkTogether';
import Reviews from '../components/main/Reviews';
import Contacts from '../pages/about-us/Contact'
import {ToastContainer} from "react-toastify";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <header>
                <Navbar/>
            </header>

            <main>
                <ToastContainer/>
                <HomePage/>
                <Logos_first_row/>
                <Map/>
                <Main_services/>
                <LetsWorkTogether/>
                <Reviews/>
                <Contacts/>
                <Footer/>
            </main>

            <footer>

            </footer>
        </div>
    )
}
